spring.application.name=auth-service
eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/authService
spring.datasource.username=postgres
spring.datasource.password=qwerty

spring.application.security.jwt.secret-key = 68566D5971337336763979244226452948404D635166546A576E5A7234753777
spring.application.security.jwt.secret-key.expiration=60000000
spring.application.security.jwt.refresh-token.expiration= 604800000


server.port=8081
