spring.application.name=auth-service

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/authService
spring.datasource.username=postgres
spring.datasource.password=qwerty