spring.application.name=product-service
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/productService
spring.datasource.username=postgres
spring.datasource.password=qwerty

server.port=0

eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka